FROM node:24-alpine

# Playwright stuff
RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    harfbuzz \
    ca-certificates \
    ttf-freefont

WORKDIR /app

COPY package*.json ./
COPY shared/package*.json ./shared/
COPY frontend/package*.json ./frontend/

RUN rm -f package-lock.json && npm install

WORKDIR /app/frontend

EXPOSE 5173

CMD ["sh", "-c", "npm run dev"]