FROM node:22-alpine

# Playwright stuff
RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    harfbuzz \
    ca-certificates \
    ttf-freefont

WORKDIR /app

COPY package*.json ./
COPY shared/package*.json ./shared/
COPY frontend/package*.json ./frontend/

RUN npm ci

WORKDIR /app/frontend

EXPOSE 5173

CMD ["npm", "run", "dev"]