FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./

# Including devDeps for tsc
RUN npm ci

COPY . .

RUN npm run build

FROM node:22-alpine AS runner

WORKDIR /app

COPY --from=builder /app/.output ./.output
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./

# Install only production deps in final image
RUN npm ci --only=production

EXPOSE 3000

CMD ["node", ".output/server/index.mjs"]