FROM node:22-slim

WORKDIR /app

COPY package*.json ./
COPY shared/package*.json ./shared/
COPY backend/package*.json ./backend/

RUN npm ci

WORKDIR /app/backend

EXPOSE 3002

CMD ["npm", "run", "dev"]