FROM node:24-alpine

WORKDIR /app

COPY package*.json ./
COPY shared/package*.json ./shared/
COPY backend/package*.json ./backend/

RUN rm -f package-lock.json && npm install

WORKDIR /app/backend

EXPOSE 3002

CMD ["sh", "-c", "npm run dev"]