FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./

# Including development dependencies for build step
RUN npm ci

COPY . .

RUN npm run build

FROM node:22-slim AS runner

WORKDIR /app

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist ./dist

# Install only production deps in final image
RUN npm ci --only=production

EXPOSE 3002

CMD ["node", "dist/server.js"]