export default defineEventHandler((event) => {
    const config = useRuntimeConfig()
    const url = config.public.url
    const noIndex = config.public.noIndex

    const lines = []

    if (noIndex) {
        lines.push("User-agent: *")
        lines.push("Disallow: /")
    } else {
        lines.push("User-agent: *")
        lines.push("Allow: /")
        lines.push("Disallow: /plan-du-site")
    }

    lines.push(`Sitemap: ${url}/sitemap_index.xml`) // sitemap_index.xml is generated by @nuxtjs/sitemap

    event.node.res.setHeader('Content-Type', 'text/plain; charset=utf-8')
    event.node.res.statusCode = 200
    return lines.join("\n")
})
