name: CI & Deploy

on:
  push:
    branches:
      - preprod
      - main
    paths:
      - ".github/workflows/*"
      - "frontend/**"
      - "backend/**"
      - "docker-compose.yml"
      - ".env.*"
  pull_request:
    branches:
      - preprod
      - main
    paths:
      - ".github/workflows/*"
      - "frontend/**"
      - "backend/**"
      - "docker-compose.yml"
      - ".env.*"

env:
  FRONTEND_IMAGE: docker.io/lalbaanthony/borreze-frontend
  BACKEND_IMAGE: docker.io/lalbaanthony/borreze-backend

jobs:
  use-tests:
    name: 🧪 Run Tests
    uses: ./.github/workflows/tests.inc.yml
  docker:
    name: 🐳 Build & Push Docker Images
    needs: [use-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.FRONTEND_IMAGE }}
            ${{ env.BACKEND_IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix=sha-

      - name: Build & push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.prod
          push: true
          tags: |
            ${{ env.FRONTEND_IMAGE }}:latest
            ${{ env.FRONTEND_IMAGE }}:${{ github.ref_name }}
            ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile.prod
          push: true
          tags: |
            ${{ env.BACKEND_IMAGE }}:latest
            ${{ env.BACKEND_IMAGE }}:${{ github.ref_name }}
            ${{ env.BACKEND_IMAGE }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-preprod:
    name: 🚧 Deploy to Preprod
    if: github.ref == 'refs/heads/preprod'
    needs: docker
    runs-on: ubuntu-latest
    environment: preprod
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PREPROD_SSH_PRIVATE_KEY }}

      - name: Create deployment directory
        run: |
          ssh -o StrictHostKeyChecking=no \
              ${{ secrets.PREPROD_SSH_USER }}@${{ secrets.PREPROD_SSH_HOST }} \
            "mkdir -p /home/${{ secrets.PREPROD_SSH_USER }}/${{ secrets.PREPROD_FOLDER }}"

      - name: Generate .env file
        run: |
          cat <<EOF > .env
          NODE_ENV=preprod
          NODE_ENV=production
          DB_DATABASE_DB=${{ secrets.PREPROD_DATABASE_DB }}
          DB_DATABASE_USER=${{ secrets.PREPROD_DATABASE_USER }}
          DB_DATABASE_PASSWORD=${{ secrets.PREPROD_DATABASE_PASSWORD }}
          DB_DBMS_PORT=${{ secrets.PREPROD_DBMS_PORT }}
          DB_DBMS_EMAIL=${{ secrets.PREPROD_DBMS_EMAIL }}
          DB_DBMS_PASSWORD=${{ secrets.PREPROD_DBMS_PASSWORD }}
          DB_BACKEND_PORT=${{ secrets.PREPROD_BACKEND_PORT }}
          DB_BACKEND_CORS_ORIGIN=${{ secrets.PREPROD_BACKEND_CORS_ORIGIN }}
          DB_BACKEND_DATABASE_LOGGING=${{ secrets.PREPROD_BACKEND_DATABASE_LOGGING }}
          DB_BACKEND_JWT_SECRET=${{ secrets.PREPROD_BACKEND_JWT_SECRET }}
          DB_BACKEND_JWT_EXPIRES=${{ secrets.PREPROD_BACKEND_JWT_EXPIRES }}
          DB_BACKEND_SMTP_HOST=${{ secrets.PREPROD_BACKEND_SMTP_HOST }}
          DB_BACKEND_SMTP_PORT=${{ secrets.PREPROD_BACKEND_SMTP_PORT }}
          DB_BACKEND_SMTP_USER=${{ secrets.PREPROD_BACKEND_SMTP_USER }}
          DB_BACKEND_SMTP_PASS=${{ secrets.PREPROD_BACKEND_SMTP_PASS }}
          DB_BACKEND_SMTP_FROM=${{ secrets.PREPROD_BACKEND_SMTP_FROM }}
          DB_FRONTEND_PORT=${{ secrets.PREPROD_FRONTEND_PORT }}
          DB_FRONTEND_URL=${{ secrets.PREPROD_FRONTEND_URL }}
          DB_FRONTEND_API_BASE_URL_SSR=${{ secrets.PREPROD_FRONTEND_API_BASE_URL_SSR }}
          DB_FRONTEND_API_BASE_URL_CLIENT=${{ secrets.PREPROD_FRONTEND_API_BASE_URL_CLIENT }}
          DB_FRONTEND_NOINDEX=${{ secrets.PREPROD_FRONTEND_NOINDEX }}
          EOF

      - name: Copy deployment files
        run: |
          scp -o StrictHostKeyChecking=no docker-compose.yml .env \
            ${{ secrets.PREPROD_SSH_USER }}@${{ secrets.PREPROD_SSH_HOST }}:/home/${{ secrets.PREPROD_SSH_USER }}/${{ secrets.PREPROD_FOLDER }}/

      - name: Remote deploy
        run: |
          ssh -o StrictHostKeyChecking=no \
              ${{ secrets.PREPROD_SSH_USER }}@${{ secrets.PREPROD_SSH_HOST }} \
            "cd /home/${{ secrets.PREPROD_SSH_USER }}/${{ secrets.PREPROD_FOLDER }} &&
              export COMPOSE_PROJECT_NAME=${{ secrets.PREPROD_FOLDER }} &&
              export FRONTEND_IMAGE=${{ env.FRONTEND_IMAGE }}:preprod &&
              export BACKEND_IMAGE=${{ env.BACKEND_IMAGE }}:preprod &&
              (docker-compose --profile production down || true) &&
              sleep 2 &&
              docker-compose --profile production pull &&
              docker-compose --profile production up -d --remove-orphans &&
              docker image prune -af &&
              docker container prune -f"

  deploy-prod:
    name: 🚀 Deploy to Prod
    if: github.ref == 'refs/heads/main'
    needs: docker
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}

      - name: Create deployment directory
        run: |
          ssh -o StrictHostKeyChecking=no \
              ${{ secrets.PROD_SSH_USER }}@${{ secrets.PROD_SSH_HOST }} \
            "mkdir -p /home/${{ secrets.PROD_SSH_USER }}/${{ secrets.PROD_FOLDER }}"

      - name: Generate .env file
        run: |
          cat <<EOF > .env
          NODE_ENV=production
          DB_DATABASE_DB=${{ secrets.PROD_DATABASE_DB }}
          DB_DATABASE_USER=${{ secrets.PROD_DATABASE_USER }}
          DB_DATABASE_PASSWORD=${{ secrets.PROD_DATABASE_PASSWORD }}
          DB_DBMS_PORT=${{ secrets.PROD_DBMS_PORT }}
          DB_DBMS_EMAIL=${{ secrets.PROD_DBMS_EMAIL }}
          DB_DBMS_PASSWORD=${{ secrets.PROD_DBMS_PASSWORD }}
          DB_BACKEND_PORT=${{ secrets.PROD_BACKEND_PORT }}
          DB_BACKEND_CORS_ORIGIN=${{ secrets.PROD_BACKEND_CORS_ORIGIN }}
          DB_BACKEND_DATABASE_LOGGING=${{ secrets.PROD_BACKEND_DATABASE_LOGGING }}
          DB_BACKEND_JWT_SECRET=${{ secrets.PROD_BACKEND_JWT_SECRET }}
          DB_BACKEND_JWT_EXPIRES=${{ secrets.PROD_BACKEND_JWT_EXPIRES }}
          DB_BACKEND_SMTP_HOST=${{ secrets.PROD_BACKEND_SMTP_HOST }}
          DB_BACKEND_SMTP_PORT=${{ secrets.PROD_BACKEND_SMTP_PORT }}
          DB_BACKEND_SMTP_USER=${{ secrets.PROD_BACKEND_SMTP_USER }}
          DB_BACKEND_SMTP_PASS=${{ secrets.PROD_BACKEND_SMTP_PASS }}
          DB_BACKEND_SMTP_FROM=${{ secrets.PROD_BACKEND_SMTP_FROM }}
          DB_FRONTEND_PORT=${{ secrets.PROD_FRONTEND_PORT }}
          DB_FRONTEND_URL=${{ secrets.PROD_FRONTEND_URL }}
          DB_FRONTEND_API_BASE_URL_SSR=${{ secrets.PROD_FRONTEND_API_BASE_URL_SSR }}
          DB_FRONTEND_API_BASE_URL_CLIENT=${{ secrets.PROD_FRONTEND_API_BASE_URL_CLIENT }}
          DB_FRONTEND_NOINDEX=${{ secrets.PROD_FRONTEND_NOINDEX }}
          EOF

      - name: Copy deployment files
        run: |
          scp -o StrictHostKeyChecking=no docker-compose.yml .env \
            ${{ secrets.PROD_SSH_USER }}@${{ secrets.PROD_SSH_HOST }}:/home/${{ secrets.PROD_SSH_USER }}/${{ secrets.PROD_FOLDER }}/

      - name: Remote deploy
        run: |
          ssh -o StrictHostKeyChecking=no \
              ${{ secrets.PROD_SSH_USER }}@${{ secrets.PROD_SSH_HOST }} \
            "cd /home/${{ secrets.PROD_SSH_USER }}/${{ secrets.PROD_FOLDER }} &&
              export COMPOSE_PROJECT_NAME=${{ secrets.PROD_FOLDER }} &&
              export FRONTEND_IMAGE=${{ env.FRONTEND_IMAGE }}:main &&
              export BACKEND_IMAGE=${{ env.BACKEND_IMAGE }}:main &&
              (docker-compose --profile production down || true) &&
              sleep 2 &&
              docker-compose --profile production pull &&
              docker-compose --profile production up -d --remove-orphans &&
              docker image prune -af &&
              docker container prune -f"
